services:
  persistence:
    image: persistence:latest
    hostname: persistence
    build: ./persistence
    ports:
      - 3306:3306
    env_file:
      - .env
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  producer:
    image: producer:latest
    hostname: producer
    build: ./producer
    depends_on:
      persistence:
        condition: service_healthy
    ports:
      - 8080:8080
    env_file:
      - .env