services:
  persistence:
    image: persistence:latest
    hostname: persistence
    build: ./persistence
    volumes:
      - ./persistence:/database
    ports:
      - 3306:3306
    env_file:
      - .env

  producer:
    image: producer:latest
    hostname: producer
    build: ./producer
    depends_on:
      persistence:
        condition: service_healthy
    ports:
      - 8080:8080
    env_file:
      - .env