name: Clean Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install bandit
        pip install pylint
        pip install -r ./Consumer/requirements.txt
        pip install -r ./Producer/requirements.txt
    - name: Analysing the code with bandit
      run: |
        bandit -r .
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=9